name: Delete ECS Cluster, Prefect agent and ECR repository

on:
  workflow_dispatch:
    region:
      description: AWS Region
      required: true
      default: us-east-1
    project:
      description: Project name (ECS Service)
      required: true
      default: prefectdataops
jobs:
  delete-stack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ github.event.inputs.region}}

      - name: Delete ECR repository
        continue-on-error: true
        run: |
          aws ecr delete-repository --repository-name "ecr_${{ github.event.inputs.project}}" --force
          aws cloudformation delete-stack --stack-name "ecr_${{ github.event.inputs.project}}"

      - name: Delete ECS agent service
        continue-on-error: true
        run: aws cloudformation delete-stack --stack-name ${{ github.event.inputs.project}}

      - name: All AWS resources deleted
        run: echo '### All AWS resources deleted! :tada:' >> $GITHUB_STEP_SUMMARY
